"""Stage 2: Divergence detection — find cognitive gaps between members.

alignment_score is computed deterministically from a structured rubric,
not freely generated by the LLM. This ensures reproducibility (O9).
"""

import json
from collections import Counter

from minddiff.services.llm import LLMProvider

DIMENSION_LABELS = {
    1: "目的理解",
    2: "状況認識",
    3: "リスク認知",
    4: "合意事項",
    5: "優先順位",
}

# PRD 4.1: 偽の収束を防ぐ。一致判定には慎重に、乖離検出には積極的に。
ALIGNMENT_SCORE_CAP = 0.90

SYSTEM_PROMPT = """\
あなたはチームの認識ギャップを検出するアナリストです。

## 最重要原則
- 一致の判定には慎重に。乖離の検出には積極的に
- 収束を断定するより、乖離を過検出する方が安全
- 各次元で最低1つの注意点を報告すること
- 入力にない情報を推測・創作しない
- rubric の boolean フィールドは必ず true または false で返す（文字列不可）

## 入力
- Stage 1 の統合結果
- メンバーの原文回答

## 出力形式（JSON）
{
  "divergences": [
    {
      "concept": "乖離している概念を一言で",
      "confidence": "高" | "中" | "低",
      "evidence": [
        "メンバー①: 「原文引用」",
        "メンバー③: 「原文引用」"
      ],
      "recommended_action": "推奨アクション"
    }
  ],
  "rubric": {
    "has_common_core": true または false（メンバー間に共通の核となる認識があるか）,
    "has_competing_goals": true または false（目的や優先順位の競合があるか）,
    "strong_evidence_count": 整数（確実な乖離を示す証拠の件数）,
    "mention_agreement_ratio": "N/M"（主要テーマへの言及一致率。例: "2/3"）,
    以下は「優先順位」次元でのみ記入する（他の次元では省略）:
    "priority_stances": {
      "personal": [
        {"member": 1, "focus": "優先事項を2-5語で", "category": "7カテゴリのいずれか", "component": "対象領域", "direction": "3方向性のいずれか"}
      ],
      "team": [同じ形式で全メンバー分]
    }
  },
  "caution": "この次元で注意すべき点"
}

## rubric の記入基準
- has_common_core: 過半数のメンバーが同じ主題・方向性に言及していれば true
- has_competing_goals: メンバー間で明示的に矛盾する目標・方針があれば true
- strong_evidence_count: 原文引用で裏付けられる乖離の数（推測を含めない）
- mention_agreement_ratio: 最重要テーマについて何人中何人が一致した認識を持っているか
### 「優先順位」次元の追加基準
この次元では個人とチームの優先順位を構造化して抽出する:
- 各メンバーの個人優先・チーム優先を focus, category, component, direction に分解する
- category は以下の7つから選ぶ:
  - "implementation"（コード実装・機能開発）
  - "design"（設計判断・アーキテクチャ）
  - "testing"（テスト設計・実行）
  - "quality"（品質基準・レビュー基準）
  - "delivery"（リリース・速度・締切）
  - "communication"（報告・ステークホルダー対応）
  - "process"（方針決定・プロセス整備）
- direction は以下の3つから選ぶ:
  - "speed"（速度・前進・加速）
  - "quality"（品質・正確性・慎重さ）
  - "alignment"（合意・方針統一・整備）
- component は原文から対象領域を自由記述する（例: "frontend", "api", "testing"）
- この次元では mention_agreement_ratio, has_common_core, has_competing_goals は省略可（code側で計算する）
"""


def _strict_bool(value, *, fail_closed_default: bool) -> bool:
    """Extract strict boolean from rubric field.

    Only Python bool True/False are accepted.
    Any other type (str, int, None, etc.) → fail_closed_default.
    """
    if isinstance(value, bool):
        return value
    return fail_closed_default


def _parse_ratio(ratio_str: str) -> float:
    """Parse "N/M" ratio string to float. Returns -1.0 on failure."""
    try:
        parts = str(ratio_str).split("/")
        if len(parts) == 2 and int(parts[1]) > 0:
            return int(parts[0]) / int(parts[1])
    except (ValueError, ZeroDivisionError):
        pass
    return -1.0


def _compute_misalignment(p_ratio: float, t_ratio: float) -> bool:
    """Deterministic misalignment from personal/team ratio divergence.

    Replaces LLM boolean judgment. Three rules:
    - Either ratio unparseable → fail-closed True
    - Ratios diverge by > 0.34 → directional mismatch
    - Both ratios < 0.5 → no coherent alignment verifiable
    """
    if p_ratio < 0 or t_ratio < 0:
        return True
    if abs(p_ratio - t_ratio) > 0.34:
        return True
    if max(p_ratio, t_ratio) < 0.5:
        return True
    return False


def compute_alignment_score(rubric: dict, dimension: int = 0) -> float:
    """Deterministically compute alignment_score from structured rubric.

    Base score = ALIGNMENT_SCORE_CAP (0.90).
    Penalties are subtracted based on rubric fields.
    Result is clamped to [0.0, ALIGNMENT_SCORE_CAP].

    Fail-closed design (PRD 4.1):
    When rubric fields are missing, malformed, or non-bool, penalties ARE applied.
    Missing/invalid data → assume divergence exists → lower score.

    For dimension 5 (優先順位), uses personal/team split ratios if available.
    """
    score = ALIGNMENT_SCORE_CAP

    # Boolean fields: strict — only bool accepted, else fail-closed default
    has_common_core = _strict_bool(rubric.get("has_common_core"), fail_closed_default=False)
    has_competing = _strict_bool(rubric.get("has_competing_goals"), fail_closed_default=True)
    has_high_conf = _strict_bool(
        rubric.get("has_high_confidence_divergence"), fail_closed_default=True
    )

    if not has_common_core:
        score -= 0.15

    if has_competing:
        score -= 0.20

    if has_high_conf:
        score -= 0.15

    # strong_evidence_count: must be int/float, else fail-closed
    strong_count = rubric.get("strong_evidence_count")
    if not isinstance(strong_count, (int, float)):
        score -= 0.10
    elif strong_count >= 3:
        score -= 0.10
    elif strong_count >= 2:
        score -= 0.05

    # mention_agreement_ratio: for Dim5, use personal/team split if available
    if dimension == 5:
        p_ratio = _parse_ratio(str(rubric.get("personal_agreement_ratio", "")))
        t_ratio = _parse_ratio(str(rubric.get("team_agreement_ratio", "")))

        if p_ratio >= 0 and t_ratio >= 0:
            # Use the lower of the two (fail-closed: worst case wins)
            ratio = min(p_ratio, t_ratio)
        else:
            # Fallback to standard ratio, or fail-closed
            ratio = _parse_ratio(str(rubric.get("mention_agreement_ratio", "")))
            if ratio < 0:
                ratio = 0.0

        # personal_team_misalignment: deterministic from ratio divergence
        misalignment = _compute_misalignment(p_ratio, t_ratio)
        if misalignment:
            score -= 0.05
    else:
        ratio = _parse_ratio(str(rubric.get("mention_agreement_ratio", "")))
        if ratio < 0:
            ratio = 0.0  # unparseable → assume no agreement

    if ratio < 0.5:
        score -= 0.15
    elif ratio < 0.75:
        score -= 0.10

    return max(0.0, min(score, ALIGNMENT_SCORE_CAP))


def build_user_prompt(
    dimension: int,
    synthesis: dict,
    responses: list[dict],
) -> str:
    """Build user prompt for divergence detection."""
    label = DIMENSION_LABELS[dimension]
    lines = [f"## 次元: {label}\n"]
    lines.append(f"### Stage 1 統合結果\n{json.dumps(synthesis, ensure_ascii=False, indent=2)}\n")
    lines.append("### メンバー原文回答")
    for i, r in enumerate(responses, 1):
        lines.append(f"#### メンバー{i}\n{r['content']}\n")
    lines.append(
        "上記を分析し、メンバー間の認識の乖離を検出してください。JSON形式で出力してください。"
    )
    return "\n".join(lines)


VALID_CATEGORIES = frozenset(
    {"implementation", "design", "testing", "quality", "delivery", "communication", "process"}
)
VALID_DIRECTIONS = frozenset({"speed", "quality", "alignment"})


def _extract_categories(stances: dict, layer: str) -> list[str]:
    """Extract validated category list from a stance layer."""
    return [
        e["category"]
        for e in stances.get(layer, [])
        if isinstance(e, dict) and e.get("category") in VALID_CATEGORIES
    ]


def _compute_agreement_ratio(categories: list[str]) -> str:
    """Compute 'N/M' from categories. N = members in clusters of size >= 2."""
    if not categories:
        return "0/0"
    agreeing = sum(c for c in Counter(categories).values() if c >= 2)
    return f"{agreeing}/{len(categories)}"


def _compute_has_common_core_from_stances(stances: dict) -> bool:
    """True if either personal or team has a majority category."""
    for layer in ("personal", "team"):
        cats = _extract_categories(stances, layer)
        if len(cats) >= 2 and max(Counter(cats).values()) > len(cats) / 2:
            return True
    return False


def _compute_has_competing_goals_from_stances(stances: dict) -> bool:
    """True if same component appears with different directions."""
    component_dirs: dict[str, set[str]] = {}
    for layer in ("personal", "team"):
        for entry in stances.get(layer, []):
            if not isinstance(entry, dict):
                continue
            comp = str(entry.get("component", "")).lower().strip()
            direction = entry.get("direction", "")
            if comp and direction in VALID_DIRECTIONS:
                component_dirs.setdefault(comp, set()).add(direction)
    return any(len(dirs) > 1 for dirs in component_dirs.values())


def _compute_has_high_confidence(divergences: list[dict]) -> bool:
    """Deterministic: True if any divergence has confidence='高'."""
    return any(d.get("confidence") == "高" for d in divergences)


def detect_divergence(
    provider: LLMProvider,
    dimension: int,
    synthesis: dict,
    responses: list[dict],
) -> dict:
    """Run Stage 2 divergence detection for a single dimension."""
    user_prompt = build_user_prompt(dimension, synthesis, responses)
    raw = provider.generate(SYSTEM_PROMPT, user_prompt)

    text = raw.strip()
    if text.startswith("```"):
        text = text.split("\n", 1)[1] if "\n" in text else text[3:]
        text = text.rsplit("```", 1)[0]

    result = json.loads(text)

    # Deterministic overrides: replace LLM booleans with computed values
    rubric = result.get("rubric", {})
    rubric["has_high_confidence_divergence"] = _compute_has_high_confidence(
        result.get("divergences", [])
    )

    # Dim5: extract → aggregate from priority_stances
    if dimension == 5:
        stances = rubric.get("priority_stances", {})
        if isinstance(stances, dict) and stances.get("personal") and stances.get("team"):
            p_cats = _extract_categories(stances, "personal")
            t_cats = _extract_categories(stances, "team")
            rubric["personal_agreement_ratio"] = _compute_agreement_ratio(p_cats)
            rubric["team_agreement_ratio"] = _compute_agreement_ratio(t_cats)
            rubric["has_common_core"] = _compute_has_common_core_from_stances(stances)
            rubric["has_competing_goals"] = _compute_has_competing_goals_from_stances(stances)

    # Compute alignment_score deterministically from rubric
    result["alignment_score"] = compute_alignment_score(rubric, dimension=dimension)

    # Ensure at least one caution point
    if not result.get("divergences") and not result.get("caution"):
        result["caution"] = "表面的には一致しているが、詳細の解釈にズレがある可能性を排除できない"

    return result


def detect_all_divergences(
    provider: LLMProvider,
    synthesis_by_dimension: dict[str, dict],
    responses_by_dimension: dict[int, list[dict]],
) -> tuple[dict, dict]:
    """Run divergence detection for all dimensions.

    Returns (divergences_dict, alignment_scores_dict).
    """
    divergences = {}
    alignment_scores = {}
    for dim in range(1, 6):
        dim_key = str(dim)
        synth = synthesis_by_dimension.get(dim_key, {})
        resps = responses_by_dimension.get(dim, [])
        if resps:
            result = detect_divergence(provider, dim, synth, resps)
            divergences[dim_key] = result.get("divergences", [])
            alignment_scores[dim_key] = result.get("alignment_score", 0.5)
        else:
            divergences[dim_key] = []
            alignment_scores[dim_key] = 0.0
    return divergences, alignment_scores
